<?php

/**
 * return random a row from the list
 */

namespace App\NameLists;


class Flavors
{
    public static function generate() {

        $list = array(

            "Acai Berry",
            "Almond",
            "Amaretto",
            "Anise",
            "Apple Banana Smoothie",
            "Apple Cider",
            "Apple Double",
            "Apple Fuji",
            "Apple Gala",
            "Granny Smith Apple",
            "Apple Hoops",
            "Apple Juice",
            "Apple Peach Smoothie",
            "Apple Pie A la Mode",
            "Cinnamon Apple Pie",
            "Red Apple",
            "Ripe Apple",
            "Apple Strudel",
            "Apple",
            "Apricot",
            "Avocado",
            "Bacon",
            "Baked Apple",
            "Banana Cream Pie",
            "Banana Custard",
            "Banana Nut Bread",
            "Banana Nut Pudding",
            "Banana Ripe",
            "Banana Split",
            "Banana",
            "Bananas Foster",
            "Barbecue",
            "Basil",
            "Bavarian Cream",
            "Beignets",
            "Belgian Waffle",
            "Berry Cola",
            "Birch Beer",
            "Black Cherry",
            "Black Currant",
            "Black Licorice",
            "Black Tea",
            "Black Walnut",
            "Blackberry Cobbler",
            "Blackberry",
            "Blood Orange",
            "Blueberry Cheesecake",
            "Blueberry Fruit",
            "Blueberry Juicy",
            "Blueberry Pie",
            "Blueberry Shortcake",
            "Blueberry",
            "Bourbon Whiskey",
            "Bourbon",
            "Boysenberry Pie",
            "Boysenberry",
            "Bread Pudding",
            "Brown Sugar",
            "Bubble Gum",
            "Bubble-Bubble Pink Gum",
            "Burnt Sugar",
            "Butter Almond",
            "Butter Milk",
            "Butter Pecan Ice Cream",
            "Butter Pecan",
            "Butter Rum",
            "Butter Toffee",
            "Butter",
            "Buttered Popcorn",
            "Butterscotch",
            "Cactus Soda",
            "Cake Batter",
            "Cake Blueberry Coco",
            "Cake Raspberry Coco",
            "Cake Yellow",
            "Cantaloupe",
            "Captain N Berries",
            "Caramel Cone",
            "Caramel Cream",
            "Caramel Custard",
            "Caramel Drizzle Cheesecake",
            "Caramel Popcorn",
            "Caramel",
            "Cardamom",
            "Caribbean Coconut",
            "Carmel Apple",
            "Carrot Cake",
            "Champagne",
            "Cheddar Cheese",
            "Cheese",
            "Cheesecake",
            "Cherry Cola",
            "Cherry Cream Spice",
            "Cherry Pie",
            "Cherry",
            "Chili",
            "Chocolate Brownie",
            "Chocolate Cake",
            "Chocolate Cheesecake",
            "Chocolate Chip Cookie",
            "Chocolate Churro",
            "Chocolate Milk",
            "Chocolate Mint",
            "Chocolate Peanut Cup",
            "Chocolate Powder",
            "Chocolate Strawberry",
            "Chocolate",
            "Churro",
            "Cinnamon Bears",
            "Cinnamon Danish Swirl",
            "Cinnamon Roll",
            "Cinnamon",
            "Citrus Punch",
            "Clove",
            "Coconut Cream Pie",
            "Coconut Milk",
            "Coconut Toasted",
            "Coconut",
            "Coffee Black",
            "Coffee",
            "Cola",
            "Concord Grape",
            "Condensed Caramel Milk",
            "Condensed Milk",
            "Cookie Dough",
            "Cookies & Cream",
            "Corn Bread",
            "Corn Puffs",
            "Corn Tortilla",
            "Cosmopolitan Martini",
            "Cranberry",
            "Cream Soda",
            "Creamy Yogurt Cheesecake",
            "Creme de Menthe",
            "Crushin Grape",
            "Crushin Orange",
            "Crème Bouquet",
            "Crème Brulee",
            "Cucumber w/Mint",
            "Cucumber",
            "Custard",
            "Dill Pickle",
            "Double Dutch Chocolate",
            "Doughnut",
            "Dr. Soda",
            "Dragon Fruit",
            "Dulce de Leche",
            "Dutch Chocolate",
            "Egg Nog",
            "Elderberry",
            "Energy Booster",
            "Energy Drink Green",
            "Energy Drink Red",
            "Energy Rock",
            "Ethyl Maltol PG",
            "Ethyl Maltol",
            "Eucalyptus",
            "Evaporated Milk",
            "Fenugreek",
            "Firni Pudding",
            "Flan",
            "French Toast",
            "Frosted Froops",
            "Fruit Mix",
            "Fruit Punch",
            "Fruity Flakes",
            "Fudge Brownie",
            "Fuzzy Navel",
            "Garlic",
            "Ginger Ale Soda",
            "Ginger Ale",
            "Ginger Beer",
            "Ginger Lime",
            "Ginger Pumpkin Spice Latte",
            "Gingerbread Cookie",
            "Gingerbread",
            "Gingersnap",
            "Girly Cookies Caramel Coco",
            "Girly Cookies Choco Mint",
            "Girly Cookies Lemonades",
            "Girly Cookies Shortbread",
            "Glazed Donut",
            "Golden Sponge Cake",
            "Graham Cracker",
            "Grand Mariner",
            "Grape Punch",
            "Grape Soda",
            "Grape",
            "Grapefruit",
            "Green Apple Caramel",
            "Green Onion",
            "Green Tea",
            "Grenadine",
            "Guava Fresh",
            "Guava Ripe",
            "Guava",
            "Gummy Bear",
            "Harvest Berry",
            "Hazelnut Chocolate Spread",
            "Hazelnut",
            "Honey Puffs",
            "Honey",
            "Honeydew Melon",
            "Horchata",
            "Hot Chile Pepper",
            "Huckleberry",
            "Iced Tea",
            "Irish Cream",
            "Irish Whiskey",
            "Jalapeño",
            "Ketchup",
            "Kettle Corn",
            "Key Lime Pie",
            "Key Lime",
            "Kiwi",
            "Lemon Bar",
            "Lemon Cheesecake",
            "Lemon Custard",
            "Lemon Lime Up Soda",
            "Lemon Lime",
            "Lemon Meringue Pie",
            "Lemon Muffin",
            "Lemon Pound Cake",
            "Lemon Tea",
            "Lemon",
            "Lemonade",
            "Lime Sorbet",
            "Lime",
            "Long Island Tea",
            "Lychee",
            "Macadamia Nut",
            "Mai Tai",
            "Malted Milk",
            "Mango Green",
            "Mango Orange Pineapple",
            "Mango Ripe",
            "Mango Sorbet",
            "Mango Sweet",
            "Mango",
            "Maple Pecan Pie",
            "Maple Syrup",
            "Maple",
            "Maraschino Cherry",
            "Margarita",
            "Marshmallow Vanilla",
            "Marshmallow White Puffy",
            "Marshmallow",
            "Marzipan",
            "Mashed Potato",
            "Melon Kiwi",
            "Melon",
            "Menthol",
            "Merlot",
            "Milk Shake Banana",
            "Milk Shake Chocolate",
            "Milk Shake Vanilla",
            "Milk Tea",
            "Milk",
            "Mint",
            "Mixed Berry",
            "Mocha Irish Cream",
            "Mocha",
            "Mojito",
            "Moscow Mule",
            "Mountain Soda",
            "Mustard",
            "Neapolitan Ice Cream",
            "New York Cheesecake",
            "Norwegian Ring Cake",
            "Nutmeg",
            "Nutty Professor PG",
            "Nutty Professor",
            "Oatmeal",
            "Onion",
            "Orange Brandy",
            "Orange Cream",
            "Orange Fresh",
            "Orange Juice",
            "Orange Mandarin",
            "Orange Mango",
            "Orange Navel",
            "Orange Pineapple",
            "Orange Popsicle",
            "Orange Sherbet Ice Cream",
            "Orange",
            "PB & J Grape Jelly",
            "Pancake",
            "Papaya",
            "Parmesan Cheese",
            "Passion Fruit",
            "Peach Cobbler",
            "Peach Fresh",
            "Peach Ripe",
            "Peach Sorbet",
            "Peach Sweet",
            "Peach",
            "Peaches & Cream",
            "Peanut Butter",
            "Peanut",
            "Pear Juicy",
            "Pear",
            "Pecan Roll",
            "Pecan",
            "Peppermint",
            "Pickle",
            "Pie Crust",
            "Pina Colada",
            "Pineapple Chile",
            "Pineapple Juice",
            "Pineapple Orange Banana Sorbet",
            "Pineapple Peach",
            "Pineapple Sherbet Ice Cream",
            "Pineapple Soda",
            "Pineapple Sorbet",
            "Pineapple Upside Down Cake",
            "Pineapple",
            "Pink Lemonade",
            "Pistachio Ice Cream",
            "Pistachio Pudding",
            "Pistachio",
            "Pitaya",
            "Pizza",
            "Plantation Punch",
            "Plum",
            "Pomegranate",
            "Pound Cake",
            "Powdered Sugar",
            "Prickly Pear",
            "Pumpkin Pie",
            "Pumpkin Spice",
            "Pumpkin",
            "Punch",
            "Quinine",
            "Rainbow Sherbet House",
            "Rainbow Sherbet Top Shelf",
            "Raisin Bread",
            "Raspberry Fresh",
            "Raspberry Ginger Ale",
            "Raspberry Lemonade",
            "Raspberry Shortcake",
            "Raspberry Sorbet",
            "Raspberry",
            "Real Honey",
            "Red Cherry Sour Balls",
            "Red Velvet",
            "Rhubarb Crisp",
            "Rice Pudding",
            "Rock and Rye",
            "Root Beer Float",
            "Root Beer",
            "Rum",
            "Rye Bread",
            "Sage",
            "Salsa",
            "Salted Caramel",
            "Sarsaparilla",
            "Sassafras",
            "Sleep Aid",
            "Smoke",
            "Smores",
            "Snickerdoodle Cookie",
            "Soft Cinnamon",
            "Sour",
            "Sourdough Bread",
            "Spearmint",
            "Spice",
            "Spiced Apple Cider",
            "Spruce",
            "Spumoni Ice Cream",
            "Squaw Bread",
            "Squirts Soda",
            "Sriracha",
            "Strawberry Cheesecake",
            "Strawberry Fresh",
            "Strawberry Fruit",
            "Strawberry Jam",
            "Strawberry Kiwi",
            "Strawberry Lemonade",
            "Strawberry Milk",
            "Strawberry Ripe",
            "Strawberry Shortcake",
            "Strawberry Souffle",
            "Strawberry Swirl",
            "Strawberry Yogurt",
            "Strawberry",
            "Strawnilla",
            "Sugar Butter Cookie",
            "Sugar Cone",
            "Sugar Liquid",
            "Sugar Plum",
            "Sweet Cream",
            "Sweet Dates",
            "Sweet Ice Cream",
            "Sweet Lemon",
            "Sweet Potato",
            "Sweet Tea",
            "S’Mores",
            "Tamarind",
            "Tangerine",
            "Tapioca Pudding",
            "Tart Lemon",
            "Tequila",
            "Teriyaki",
            "Thai Tea",
            "Tiramisu",
            "Toasted Coconut",
            "Toasted Flakes",
            "Toasted Marshmallow",
            "Toffee",
            "Tonic",
            "Trio Berry",
            "Tropical Blend",
            "Tropical Punch",
            "Tutti Frutti",
            "Vanilla Bean Ice Cream",
            "Vanilla Butternut",
            "Vanilla Cola",
            "Vanilla Cream",
            "Vanilla Cupcake",
            "Vanilla Custard Cheesecake",
            "Vanilla Custard",
            "Vanilla French",
            "Vanilla Frosting",
            "Vanilla Ice Cream Shake",
            "Vanilla Maple",
            "Vanilla Pudding",
            "Vanilla Strawberry Honey",
            "Vanilla Wafer",
            "Vanilla",
            "Wasabi",
            "Watermelon Bang",
            "Watermelon Double",
            "Watermelon Fresh",
            "Watermelon Rocks Fizz",
            "Watermelon",
            "Wheat Bread",
            "Whipped Cream",
            "White Chocolate Kip Kap",
            "White Chocolate Mac Nut",
            "White Chocolate Mocha",
            "White Chocolate",
            "White Tea",
            "Wild Berry",
            "Wild Cherry Cream",
            "Wild Cherry",
            "Wintergreen",


        );

        $count = count($list) - 1;

        $k = rand(0,$count);

        return $list[$k];

    }
}
